//Uniform sets definition
ARTR_irregularUniforms = [
	[
		"guerrilla",
		["U_BG_Guerilla2_3","U_BG_Guerrilla_6_1","U_BG_Guerilla1_1","U_BG_Guerilla2_2","U_BG_Guerilla2_1","U_I_G_resistanceLeader_F","U_BG_Guerilla1_2_F"]
	],
	[
		"paramilitary",
		["U_I_C_Soldier_Para_1_F","U_I_C_Soldier_Para_4_F","U_I_C_Soldier_Para_5_F","U_I_C_Soldier_Para_3_F","U_I_C_Soldier_Para_2_F"]
	],
	[
		"bandit",
		["U_I_C_Soldier_Bandit_3_F","U_I_C_Soldier_Bandit_5_F","U_I_C_Soldier_Bandit_2_F","U_I_C_Soldier_Bandit_1_F","U_I_C_Soldier_Bandit_4_F"]
	],
	[
		"civilian",
		["U_C_Man_casual_1_F","U_C_Man_casual_3_F","U_C_Man_casual_2_F","U_C_Mechanic_01_F"]
	],
	[
		"civilianShorts",
		["U_C_Man_casual_5_F","U_C_Man_casual_4_F","U_C_Man_casual_6_F","U_C_Poloshirt_tricolour","U_C_Poloshirt_stripped","U_C_Poloshirt_salmon","U_C_Poloshirt_redwhite","U_C_Poloshirt_burgundy","U_C_Poloshirt_blue"]
	],
	[
		"civilianSports",
		["U_C_man_sport_2_F","U_C_man_sport_3_F","U_C_man_sport_1_F"]
	],
	[
        "IDAP",
        ["U_C_IDAP_Man_cargo_F","U_C_IDAP_Man_Jeans_F","U_C_IDAP_Man_casual_F","U_C_IDAP_Man_shorts_F","U_C_IDAP_Man_Tee_F","U_C_IDAP_Man_TeeShorts_F"]
    ],
	[
		"construction",
		["U_C_ConstructionCoverall_Black_F","U_C_ConstructionCoverall_Blue_F","U_C_ConstructionCoverall_Red_F""U_C_ConstructionCoverall_Vrana_F"]
	]
];

//Vest sets definition
ARTR_irregularVests = [
	[
		"plateCarrier",
		["V_PlateCarrier2_rgr_noflag_F","V_PlateCarrier2_blk","V_PlateCarrier1_rgr_noflag_F","V_PlateCarrier1_blk"]
	],
	[
		"chestRig",
		["V_Chestrig_oli","V_Chestrig_khk","V_Chestrig_rgr","V_Chestrig_blk"]
	],
	[
		"chestRigTactical",
		["V_TacChestrig_oli_F","V_TacChestrig_grn_F","V_TacChestrig_cbr_F"]
	],
	[
		"bandolier",
		["V_BandollierB_oli","V_BandollierB_blk","V_BandollierB_cbr","V_BandollierB_rgr","V_BandollierB_khk"]
	],
	[
	 	"tacVest",
	 	["V_TacVest_oli","V_TacVest_khk","V_TacVest_camo","V_TacVest_brn","V_TacVest_blk"]
	],
	[
		"safety",
		["V_Safety_blue_F","V_Safety_orange_F","V_Safety_yellow_F"]
	],
	[
		"multipocket",
		["V_Pocketed_black_F","V_Pocketed_coyote_F","V_Pocketed_olive_F"]
	],
	[
		"legstrap",
		["V_LegStrapBag_black_F","V_LegStrapBag_coyote_F","V_LegStrapBag_olive_F"]
	]
];

//Headgear sets definition
ARTR_irregularHeadgear = [
	[
		"bandanna",
		["H_Bandanna_camo","H_Bandanna_sand","H_Bandanna_sgg","H_Bandanna_mcamo","H_Bandanna_khk","H_Bandanna_gry","H_Bandanna_blu","H_Bandanna_cbr"]
	],
	[	"beanie",
		["H_Watchcap_khk","H_Watchcap_camo","H_Watchcap_cbr","H_Watchcap_blk"]
	],
	[
		"boonie",
		["H_Booniehat_tan","H_Booniehat_oli","H_Booniehat_khk"]
	],
	[
		"cap",
		["H_Cap_tan","H_Cap_red","H_Cap_oli","H_Cap_grn","H_Cap_blu","H_Cap_blk"]
	],
	[
		"hat",
		["H_Hat_tan","H_Hat_grey","H_Hat_checker","H_Hat_camo","H_Hat_brown","H_Hat_blue"]
	],
	[
		"helmet",
		["H_HelmetB_snakeskin","H_HelmetB_sand","H_HelmetB_grass","H_HelmetB_desert","H_HelmetB_black","H_HelmetB"]
	],
	[
		"ech",
		["H_HelmetSpecB_snakeskin","H_HelmetSpecB_sand","H_HelmetSpecB_paint1","H_HelmetSpecB_paint2","H_HelmetSpecB_blk","H_HelmetSpecB"]
	],
	[
		"ich",
		["H_HelmetB_light_snakeskin","H_HelmetB_light_sand","H_HelmetB_light_grass","H_HelmetB_light_desert","H_HelmetB_light_black","H_HelmetB_light"]
	],
	[
		"milcap",
		["H_MilCap_dgtl","H_MilCap_tna_F","H_MilCap_mcamo","H_MilCap_ocamo","H_MilCap_gry"]
	],
	[
		"shemagh",
		["H_ShemagOpen_khk","H_ShemagOpen_tan","H_Shemag_olive"]
	],
    [
        "idapcap",
        ["H_Cap_Black_IDAP_F","H_Cap_Orange_IDAP_F","H_Cap_White_IDAP_F"]
    ],
    [
        "pasgt",
        ["H_PASGT_basic_blue_F","H_PASGT_basic_olive_F","H_PASGT_basic_white_F"]
    ],
    [
        "earpro",
        ["H_EarProtectors_black_F","H_EarProtectors_orange_F","H_EarProtectors_red_F","H_EarProtectors_white_F","H_EarProtectors_yellow_F"]
    ],
    [
        "hardhat",
        ["H_Construction_basic_black_F","H_Construction_basic_black_F","H_Construction_basic_orange_F","H_Construction_basic_red_F","H_Construction_basic_white_F",",_Construction_basic_yellow_F","H_Construction_basic_vrana_F","H_Construction_earprot_black_F","H_Construction_earprot_orange_F","H_Construction_earprot_red_F","H_Construction_earprot_white_F","H_Construction_earprot_,ellow_F","H_Construction_earprot_vrana_F","H_Construction_headset_black_F","H_Construction_headset_orange_F","H_Construction_headset_red_F","H_Construction_headset_white_F","H_Construction_headset_,ellow_F","H_Construction_headset_vrana_F"]
    ],
    [
        "bandage",
        ["H_HeadBandage_clean_F","H_HeadBandage_stained_F","H_HeadBandage_bloody_F"]
    ],
    [
        "headset",
        ["H_HeadSet_black_F","H_HeadSet_orange_F","H_HeadSet_red_F","H_HeadSet_white_F","H_HeadSet_yellow_F"]
    ],
    [
        "presshelm",
        ["H_PASGT_basic_blue_press_F","H_PASGT_neckprot_blue_press_F"]
    ],
    [
        "safarihat",
        ["H_Hat_Safari_olive_F","H_Hat_Safari_sand_F"]
    ],
    [
        "earpiece",
        ["H_WirelessEarpiece_F"]
    ]
];

//Goggle sets definition
ARTR_irregularGoggles = [
	[
		"balaclava",
		["G_Balaclava_oli","G_Balaclava_blk"]
	],
	[
		"bandanna",
		["G_Bandanna_tan","G_Bandanna_sport","G_Bandanna_shades","G_Bandanna_oli","G_Bandanna_beast","G_Bandanna_blk","G_Bandanna_khk"]
	],
	[
		"shades",
		["G_Shades_Red","G_Shades_Green","G_Shades_Blue","G_Shades_Black"]
	],
	[
		"shadesSport",
		["G_Sport_Greenblack","G_Sport_Blackred","G_Sport_Checkered","G_Sport_BlackWhite","G_Sport_Blackyellow","G_Sport_Red"]
	],
	[
		"respirator",
		["G_Respirator_blue_F","G_Respirator_white_F","G_Respirator_yellow_F"]
	],
	[
		"eyepro",
		["G_EyeProtectors_F","G_EyeProtectors_Earpiece_F"]
	],
	[
		"earpiece",
		["G_WirelessEarpiece_F"]
	]
];

//Backpack sets definition
ARTR_irregularBackpacks = [
	[
		"tactical",
		["B_TacticalPack_oli","B_TacticalPack_rgr","B_TacticalPack_blk"]
	],
	[
		"kitbag",
		["B_Kitbag_sgg","B_Kitbag_rgr","B_Kitbag_cbr"]
	],
	[
		"fieldpack",
		["B_FieldPack_oli","B_FieldPack_khk","B_FieldPack_cbr","B_FieldPack_blk"]
	],
	[
		"carryall",
		["B_Carryall_oli","B_Carryall_khk","B_Carryall_cbr"]
	],
	[
		"assault",
		["B_AssaultPack_sgg","B_AssaultPack_khk","B_AssaultPack_rgr","B_AssaultPack_blk","B_AssaultPack_cbr"]
	],
	[
        "legstrap",
        ["B_LegStrapBag_black_F","B_LegStrapBag_coyote_F","B_LegStrapBag_olive_F"]
    ],
    [
        "messengerbag",
        ["B_Messenger_Black_F","B_Messenger_Coyote_F","B_Messenger_Gray_F","B_Messenger_Olive_F"]
    ]
];
